dependencies:
  build:
    - ruby:2.6.0

build_targets:
  - name: default
    commands:
      - gem install bundler -v 1.8
      - bundle install
      - rspec ./spec/error_spec.rb
      - rspec ./spec/async_spec.rb
      - rspec ./spec/response_spec.rb
      - rspec ./spec/synchronous_spec.rb
      - rspec ./spec/websocket_spec.rb
      
    tags:
     channel: experimental

ci:
  builds:
    - name: tests
      build_target: default



