dependencies:
  build:
    - ruby:2.6.0

 

build_targets:
  - name: default
    commands:
      - gem install bundler -v 1.8
      - bundle install
      - ruby ./spec/error_spec.rb

ci:
  builds:
    - name: android_build
      build_target: default



